version: '3.8'

services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=7779;applicationname=TimerApp;
    ports:
       - "8080:80"

volumes:
  pgdata:
